const SAVE_SHOPIFY_DATA = 'SAVE_SHOPIFY_DATA'
const SHOP_EXISTS = 'SHOP_EXISTS'
const SHOP_NOT_EXISTS = 'SHOP_NOT_EXISTS'

export default {
    SAVE_SHOPIFY_DATA,
    SHOP_EXISTS,
    SHOP_NOT_EXISTS
}